[tool.poetry]
name = "pydentity-core"
version = "0.1.0"
description = ""
authors = ["Raden <raden@zynosstudios.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
easy-id = "^1.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
